version: 1.0.0.{build}
os: WMF 5

branches:
  only:
    - master

skip_commits:
  files:
    - README.md

init:
  - git config --global core.autocrlf false

install:
  - ps: |
      Install-PackageProvider -Name NuGet -Force | Out-Null
      Install-Module -Name Pester -Scope CurrentUser -Force | Out-Null

build: off

test_script:
  - ps: |
      $testSource = Join-Path $Env:APPVEYOR_BUILD_FOLDER test -Resolve
      $testResultsFile = Join-Path $Env:APPVEYOR_BUILD_FOLDER testResults.xml
      $res = Invoke-Pester -Path $testSource -CI -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($Env:APPVEYOR_JOB_ID)", $testResultsFile)
      if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
